### ISSUE TITLE
Docs: Need a full key list of localization #107

### ISSUE THREAD

**Issue by dongsik-yoo** [nhnent/tui.image-editor#110]
## Version

Latest

## Development Environment

Mac, Chrome

## Current Behavior

The feature localization PR #107  was merged. Thanks to @anton-marchenko.
There is only minimum example like below.

```js
var locale_ru = { // override default English locale to your custom
    'Crop': 'Обзрезать',
    'Delete-all': 'Удалить всё'
    // etc...
};
```

## Expected Behavior

We also need a full key list of localization.

**Comment by anton-marchenko** [comment]
I will make doc today.

**Comment by jinwoo-kim-nhn** [comment]
resolved
