### ISSUE TITLE
Unable to select custom colors via colorpicker field

### ISSUE THREAD

**Issue by qman33** [nhnent/tui.image-editor#131]
## Version
3.4.0

## Development Environment
Chrome 71, Windows 10
FireFox 64, Windows 10

## Current Behavior
The colorpicker does allow the selection of a custom color via hex text input or the colorpicker button. The tui.color-picker appears in the DOM but is set to `display: none`. This applies to all colorpickers (tint, multiply, blend, draw, shape stroke, shape fill, icon, and text). Reproducible in example01: https://www.screencast.com/t/zcSO2yra

## Expected Behavior
Clicking on the hex text field should not hide the `.color-picker-control` div and allow editing of the field. Additionally, clicking on the `.tui-colorpicker-palette-toggle-slider` input should open up the tui.color-picker field to allow the selection of a custom color.

**Comment by junghwan-park** [comment]
@qman33 
I got this. Thanks!

**Comment by nao-pon** [comment]
@junghwan-park Hexadecimal color can now be entered in v3.5.0. However, the color picker is still not displayed.
