### ISSUE TITLE
Load Button in Image editor UI does not work/function in Firefox browser

### ISSUE THREAD

**Issue by Sai-Teja-Payyavula** [nhnent/tui.image-editor#137]
## Version
 v3.3.0 

## Development Environment
Mozilla Firefox, Window 7 OS

## Current Behavior
Doesnt throw an error or bug when its clicked in Mozilla browser.
Usually load button works in other browsers.
Even in the demo page the load button isnt working. 
http://nhnent.github.io/tui.image-editor/latest/tutorial-example01-includeUi.html

## Expected Behavior
 Working load funcion 

Thank You.

**Comment by dannymick** [comment]
I'm getting a `TypeError: e is null` error around `tui-image-editor.min.js:8:25404` whenever I click the Load button in FF65.

**Comment by arifhussain353** [comment]
I can confirm this issue. In `Firefox v65.0 (64-bit)` load button not working.

**Comment by junghwan-park** [comment]
@arifhussain353 
Thanks. I'll fix this right away.
