### ISSUE TITLE
Help. I cannot import module in React typescript

### ISSUE THREAD

**Issue by diegoclerici** [nhnent/tui.image-editor#142]
## Version

latest version

## Development Environment

I'm working with React latest version with Typescript (create-react-app-ts) and material-ui latest version

## Current Behavior

I cannot import the module "tui-image-editor" using import sentence for modules by Typescript. 
There isn't a default export in the index.d.ts file I guess.

I tried: 
```js
// Write example code
import * as tui from 'tui-image-editor'
```
Get this error: (70,22): Module ''tui-image-editor'' resolves to a non-module entity and cannot be imported using this construct.

## Expected Behavior
import module 'tui-image-editor' and use ImageEditor class.

**Comment by junghwan-park** [comment]
@diegoclerici 
You should use **default exported** `tui-image-editor` constructor.

```js
import ImageEditor from 'tui-image-editor';
```

**Comment by diegoclerici** [comment]
Hi junghwan-park! Thank you for your time. 
I tried that but: 

<img width="683" alt="captura de pantalla 2019-02-12 a la s 23 11 29" src="https://user-images.githubusercontent.com/10518642/52681725-a6c40f00-2f1b-11e9-9d34-c033b0a48c0a.png">

If change this within tui-image-editor/index.d.ts:

`
declare module 'tui-image-editor' {
  export = tuiImageEditor.ImageEditor;
}
`

with: 

`declare module 'tui-image-editor' {
  export default tuiImageEditor.ImageEditor;
}
`

Then the sentence you propose: 
`import ImageEditor from 'tui-image-editor';`

It works. Any ideas ? What I'm missing?

Thank you

**Comment by junghwan-park** [comment]
@diegoclerici 
Oh, I found the reason. TOAST UI Image-Editor `index.d.ts` was written based on **vue-cli**'s default `tsconfig.json`. And it has `allowSyntheticDefaultImports` and `esModuleInterop` properties being set `true`.

I think I change `test/types/tsconfig.json` optional properties to Typescript compiler default, for `test/types/type-tests.ts`. And `index.d.ts` ether. I'll work on this and release next release.
Thank you for your reporting.  :)

**Comment by diegoclerici** [comment]
> @diegoclerici
> Oh, I found the reason. TOAST UI Image-Editor `index.d.ts` was written based on **vue-cli**'s default `tsconfig.json`. And it has `allowSyntheticDefaultImports` and `esModuleInterop` properties being set `true`.
> 
> I think I change `test/types/tsconfig.json` optional properties to Typescript compiler default, for `test/types/type-tests.ts`. And `index.d.ts` ether. I'll work on this and release next release.
> Thank you for your reporting. :)

Oh @junghwan-park Thank you! Temporally I will set `allowSyntheticDefaultImports` and `esModuleInterop` properties to true in my project.

Best regards!

I will waiting for the next release as well
