### ISSUE TITLE
v3.5.1. broken Image Editor instantiation

### ISSUE THREAD

**Issue by dannymick** [nhnent/tui.image-editor#152]
## Version
v3.5.1.

## Development Environment
Chrome, Safari, FF

## Current Behavior
There's a breaking change in v3.5.1 where I cannot instantiate the image editor. I noticed the demo on the website (https://ui.toast.com/tui-image-editor/) is broken, as well.

```
Slader.ImageEditor.tui = new tui.ImageEditor(tuiCanvas, {
    includeUI: {
        loadImage: {
	    "path": source,
	    "name": source,
	},
	theme: blackTheme,
	initMenu: 'filter',
	menuBarPosition: 'bottom'
    },
    cssMaxWidth: 700,
    cssMaxHeight: 500
});
```

## Error Message
```
Uncaught TypeError: Cannot read property 'create' of undefined
    at new e (tui-image-editor.min.js:7)
    at new t (tui-image-editor.min.js:18)
    at tui-image-editor.min.js:18
    at r (tui-code-snippet.min.js:7)
    at Object.i [as forEach] (tui-code-snippet.min.js:7)
    at e.value (tui-image-editor.min.js:18)
    at new e (tui-image-editor.min.js:18)
    at new e (tui-image-editor.min.js:10)
```

## Expected Behavior
Image Editor should work as normal

**Comment by junghwan-park** [comment]
@dannymick 

You should add `postinstall` **npm script** to your `package.json` for install `fabric`.

```js
{
  // ...
  "scripts": {
    // ...
    "postinstall": "npm install --no-save --no-optional fabric@^1.6.7"
  },
  // ...
}
```

`postinstall` will automatically executed by `npm install`.

Executing `npm install tui-image-editor` command or add `tui-image-editor` to your dependency
 and `npm install` for the first time, `tui-image-editor`\`s `postinstall` script will called.
If you hit `npm install` again, `your_project_root/node_modules/tui-image-editor/node_modules/fabric` will be removed and it will not installed again.

This is not a breaking change but lack of information of dependency installation guide.
The README.md will be edited very soon. Sorry for your inconvenience.

**Comment by dannymick** [comment]
Thanks @junghwan-park!
