### ISSUE TITLE
SVG Icons are not loading in CRA project

### ISSUE THREAD

**Issue by NZOleg** [nhnent/tui.image-editor#155]
## Version

"tui-image-editor": "^3.5.1"
## Development Environment

Ubuntu 18.04
Browser: Chrome 72

## Current Behavior
Tui image editor does not load SVGs properly and therefore they are not displayed in React Project

```js
    componentDidMount = () => {
        this.instance = new imageEditor(document.querySelector('#test'), {
            includeUI: {
                loadImage: {
                    path: testImage,
                    name: 'SampleImage'
                },
                theme: blackTheme,
                initMenu: 'filter',
                menuBarPosition: 'bottom'
            },
           cssMaxWidth: 700,
           cssMaxHeight: 500,
           selectionStyle: {
               cornerSize: 20,
               rotatingPointOffset: 70
           }
       });
}

render(){
<div id="test" />
}
```

As I can see from Network tab in console, image editor is trying to get icons from root directory (and gets react page back) rather than getting it from node_modules. The same  behaviour when using it from cdn for tui.image-editor. All dependancies are loaded through cdn as it's the only way I found. There are one issue on stackoverflow related to the editor, but for VueJs, so I assume there are some webpack problems. (My project using default CRA webpack)

## Expected Behavior
SVGs are loaded and rendered properly

**Comment by junghwan-park** [comment]
@NZOleg 
You installed TOAST UI ImageEditor via `npm`? So, I think you should copy icon SVGs for use TOAST UI ImagEditor to your APP.

Your application has all dependency of `icon-*.svg` files are should copied your application and serve that icons in your server directory. And you can change `icon-*.svg` path [themeConfig](https://nhnent.github.io/tui.image-editor/latest/global.html#themeConfig) via `option.theme` object\`s property:

```js
{
// ...
    // submenu icons
    'submenu.normalIcon.path': 'static-resources/svg/icon-a.svg'
// ...
}
```

**Comment by NZOleg** [comment]
@junghwan-park 
Thank you for a quick response,
I just found a solution by copying theme file and requiring all svgs locally before passing  them to imageEditor constructor.

Seems like there there is some conflict in webpack. If I don't pass theme at all, I'll be able to get the same problem as described.

**Comment by KunalBurangi** [comment]
Hey can you be more specific i am unable to solve this issue please help

**Comment by KunalBurangi** [comment]
> @junghwan-park
> Thank you for a quick response,
> I just found a solution by copying theme file and requiring all svgs locally before passing them to imageEditor constructor.
> 
> Seems like there there is some conflict in webpack. If I don't pass theme at all, I'll be able to get the same problem as described.

still unable to solve the problem can you tell the steps to do so ?
