### ISSUE TITLE
I am not able to write text.

### ISSUE THREAD

**Issue by sagarvibrant** [nhnent/tui.image-editor#158]
I am not able to write text and i get this error while click on canvas:

ERROR ReferenceError: imageEditor is not defined at ImageEditor._onAddText (tui-image-editor.js:1870)

**Comment by junghwan-park** [comment]
@sagarvibrant 
Please, let me know what your code examples and developing environment. And follow our issue template guideline.
- link: https://github.com/nhnent/tui.image-editor/blob/master/docs/ISSUE_TEMPLATE.md

**Comment by sagarvibrant** [comment]
I was Implement in Angular 5 project. 

------------------------------------Code: (Typescript) ------------------------

import { Component, OnInit } from '@angular/core';
import 'tui-image-editor/dist/svg/icon-a.svg';
import 'tui-image-editor/dist/svg/icon-b.svg';
import 'tui-image-editor/dist/svg/icon-c.svg';
import 'tui-image-editor/dist/svg/icon-d.svg';
@Component({
  selector: 'app-template-tool',
  templateUrl: './template-tool.component.html',
  styleUrls: ['./template-tool.component.css']
})
export class TemplateToolComponent implements OnInit {
  constructor() { }
  ngOnInit() {
    this.tuiEditor();
  }

  tuiEditor() {

    const icona = require('tui-image-editor/dist/svg/icon-a.svg')
    const iconb = require('tui-image-editor/dist/svg/icon-b.svg')
    const iconc = require('tui-image-editor/dist/svg/icon-c.svg')
    const icond = require('tui-image-editor/dist/svg/icon-d.svg')
    //const bg = require('tui-image-editor/examples/img/bg.png')
    var blackTheme = { // or white
      // main icons
      'menu.normalIcon.path': icond,
      'menu.activeIcon.path': iconb,
      'menu.disabledIcon.path': icona,
      'menu.hoverIcon.path': iconc,
      'submenu.normalIcon.path': icond,
      'submenu.activeIcon.path': iconc,
      'common.bi.image': 'https://www.vibrantprintshop.com/assets/Images/logo/logonew.png',
      'common.bisize.width': '150px',
      'common.bisize.height': '70px',
      'common.backgroundImage': 'none',
      'common.backgroundColor': '#1e1e1e',
      'common.border': '0px',
    }
    var ImageEditor = require('tui-image-editor');
      var myEditor = new ImageEditor(document.querySelector('#tui-image-editor'), {
      includeUI: {
        loadImage: {
          path: 'img/sampleImage.jpg',
          name: 'SampleImage'
        },
        theme: blackTheme, // or whiteTheme
        menu: ['crop', 'flip', 'rotate', 'draw', 'shape', 'icon', 'text', 'mask', 'filter'],
        initMenu: 'filter',
        menuBarPosition: 'bottom'
      },
      cssMaxWidth: 700,
      cssMaxHeight: 1000,
      selectionStyle: {
        cornerSize: 20,
        rotatingPointOffset: 70
      },
    });
  }
}

--------------------------HTML-----------------------------------

<div id="tui-image-editor"></div>

**Comment by sagarvibrant** [comment]
Not Working in Linux only

**Comment by sagarvibrant** [comment]
link : https://www.vibrantprintshop.com/newtool?categoryname=Business%20Card&customSize=false&finish=White%20Plastic%20Business%20Cards&paper=Standard&size=2.125%20X%203.375%20inch&corner=Standard%20Corners&color=Print%20Both%20Sides&orientation=Horizontal&papertickness=14PT%20C2S

**Comment by junghwan-park** [comment]
@sagarvibrant 
Sorry for late reply. It seems to works well. Did you added `addText` event listener before?
