### ISSUE TITLE
Multiple object opeartion issue.

### ISSUE THREAD

**Issue by Dipak26** [nhnent/tui.image-editor#19]
when I add two objects on canvas I can not modified the previous object like I add two text or images then I can not rotate move first text or image

**Comment by Dipak26** [comment]
IN dev tools I got these warning 

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
_onMouseMove @ fabric.js:10069
fabric.js:1873 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by dongsik-yoo** [comment]
OK, please write helpful information.




## Version


## Development Environment


## Current Behavior


```js
// Write example code
```

## Expected Behavior

**Comment by Dipak26** [comment]
Version 
Android 7.0
Development Environment 
Android Studio(ionic angular android app)
Current Behavior 
if I added two images in canvas than first image rotation and resize controller are not visible some times and not work.

Expected Behavior
work for all added thing on canvas.

**Comment by dongsik-yoo** [comment]
Do you use `addImageObject` API to add image?
I want you to give me a test page to reproduce it.

**Comment by Dipak26** [comment]
it has API through which I add fixed size canvas on big image and editing inside canvas only after that I save the complete image. I will show you an image what I required.

![daniel](https://user-images.githubusercontent.com/8254127/29762704-8dbe8bde-8bed-11e7-8dde-4852dc24f461.jpg)

**Comment by Dipak26** [comment]
inside this, i required adding canvas on pillow area only.

**Comment by dongsik-yoo** [comment]
I guess you want one background image and one bird image, right?
I think this codes might help you.
```js
imageEditor.loadImageFromURL(backgroundImageUrl, imageName).then(result => {
    imageEditor.addImageObject(birdImageUrl);
});
```

`loadImageFromURL` set an image as background image. And the background image is not selectable object. You can only select other objects(Shape, Text, Image etc).

**Comment by Dipak26** [comment]
I want only selectable area as a canvas and add text and image only in this area.

![daniel](https://user-images.githubusercontent.com/8254127/29769033-27079ffc-8c06-11e7-8c02-5d636dadc645.jpg)

**Comment by Dipak26** [comment]
it is single product image and I want canvas on the only selectable area on this image means I don't want to add text and image outside this area like product personalization on E-commerce.

**Comment by dongsik-yoo** [comment]
I don't understand your issue.
Is this a bug or request?

What I understand about this issue is...
- You can't modify first attached object(text or image).
- You can add text and image, but you don't want to edit any objects outside some area.

And what version of ImageEditor do you use?

**Comment by Dipak26** [comment]
Yes, you I exactly want this and  I am using  the  tui-image-editor.js
 * @version 2.0.0
 I tried to set canvas size using adjustCanvasSize method but it also resizes the first attached image.

**Comment by Dipak26** [comment]
I want to canvas area on image not want to add a background image of the canvas.

**Comment by dongsik-yoo** [comment]
Do you mean that `adjustCanvasSize` is`resizeCanvasDimension()`?

There is no editing functionality to edit specific area only.

**Comment by Dipak26** [comment]
okay, but how I implement in this code with fabric js

**Comment by dongsik-yoo** [comment]
No more conversation.
