### ISSUE TITLE
 Multiple image object add then previous object not selectable

### ISSUE THREAD

**Issue by Dipak26** [nhnent/tui.image-editor#20]
when I add two image object on canvas then the side corners and first image object is not selectable so I can not perform resize and rotate operation on the previously added object.

**Comment by dongsik-yoo** [comment]
This issue is closed because it's description is not sufficient. Use issue template which is auto generated. In addition to, your api usage will be helpful.

**Comment by joker585** [comment]
I meet this question when I consecutive addText, and can use `imageEditor.discardSelection()` before addText to deal this question.
