### ISSUE TITLE
Can you please tell me how you can change the canvas width height according to background image load.

### ISSUE THREAD

**Issue by unitedsol** [nhnent/tui.image-editor#23]
Can you please tell me how you can change the canvas width height according to background image load with its uppar canvas and lower canvas and rest of canvas container was 100% both height and width.

Regards

**Comment by dongsik-yoo** [comment]
Sorry for late answer.
tui-image-editor uses [Canvas.setDimensions()](http://fabricjs.com/docs/fabric.Canvas.html#setDimensions) fabric API for that. fabricjs provides two options(cssOnly, backstoreOnly) with resizing canvas.

In tui-image-editor, you can see the usage at [graphics.js](https://github.com/nhnent/tui.image-editor/blob/production/src/js/graphics.js#L378).

I hope this will help you.

**Comment by unitedsol** [comment]
No its ok, Thankyou for reply,

I can try this solution in my project and if i have any issue i can let you know. Can you please give me your email this will be really appreciated.

Thanks in advance.

Regards

**Comment by dongsik-yoo** [comment]
Are you using **tui-image-editor**?
Any issue is welcome. Several maintainers will take it.
Please leave a github issue.
Thank you.

**Comment by unitedsol** [comment]
No I am working an application in which i can use fabric js.
