### ISSUE TITLE
How to add multiple text

### ISSUE THREAD

**Issue by dpqduong** [nhnent/tui.image-editor#26]
## Version

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.6.7/fabric.js"></script>
--
  | <script type="text/javascript" src="https://cdn.rawgit.com/nhnent/tui.code-snippet/v1.2.5/dist/tui-code-snippet.js"></script>
  | <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  | <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
  | <script type="text/javascript" src="https://cdn.rawgit.com/nhnent/tui.component.colorpicker/1.0.2/dist/colorpicker.min.js"></script>
  | <script type="text/javascript" src="http://nhnent.github.io/tui.image-editor/latest/dist/tui-image-editor.js"></script>
```

## Development Environment

Windows 7, browser : Google Chrome
## Current Behavior

```js
// Write example code

imageEditor.loadImageFromURL('img/sampleImage.jpg', 'SampleImage').then(sizeValue => {
    console.log(sizeValue);
	imageEditor.addText('hello 1', {
        position: {
					x: 100,
					y: 100
				}
    });
    imageEditor.deactivateAll();

	imageEditor.addText('hello 2', {
        position: {
					x: 300,
					y: 300
				}
    });

    imageEditor.clearUndoStack();
});
```

## Expected Behavior

I want add multiple text but error here 

```
tui-image-editor.js:1795 Uncaught (in promise) The executing command state is locked.
execute @ tui-image-editor.js:1795
execute @ tui-image-editor.js:571
addText @ tui-image-editor.js:1062
imageEditor.loadImageFromURL.then.sizeValue @ service-basic.js:1063
Promise resolved (async)
(anonymous) @ service-basic.js:1053
```

Please help me. Thank you so much

**Comment by jinwoo-kim-nhn** [comment]
We are analyzing this problem. We will notify you when the issue is resolved. thank you.

**Comment by jinwoo-kim-nhn** [comment]
@dpqduong
- Since the order of execution of comand must be guaranteed for history, other commands can not be executed consecutively during execution of one command.
- It should be able to guarantee the sequential execution by using promise when executing continuous command.

**Comment by safiyabsetec** [comment]
I am using your image editor plugin.I need to adddtext  with multiple text.if i am adding text one text after then first text x and y to jump where.If i click in that canvas then first text alone also jumping.

**Comment by yayapipi** [comment]
Here is an alternative solution:

`imageEditor.addText('init text', {
    styles: {
        fill: '#000',
        fontSize: 20,
        fontWeight: 'bold'
    },
    position: {
        x: 10,
        y: 10
    }
}).then(objectProps => {
    console.log(objectProps.id);
    //Add Your Second Text Here
    imageEditor.addText('init text 2');
});`
