### ISSUE TITLE
Loading image as DataURL in Canvas instead of using physical file

### ISSUE THREAD

**Issue by Anjali-Bansal** [nhnent/tui.image-editor#31]
Hi,

I am using this TUI-ImageEditor to manipulate my image. My input format id dataURI. So I don't need the load button as in samples to upload the image.

Is there any way to load DataUrl in canvas instead of sampleImage.png 

I could see I need to modify this method:

imageEditor.loadImageFromURL 

Can you please tell me, how to achieve this?

Thanks!
Anjali Bansal

**Comment by jinwoo-kim-nhn** [comment]
@Anjali-Bansal 
you editing use line 926 in example/js/service-basic.js for this issue.

However, service-basic.js is just a sample to show an example of using the API of ImageEditor.
You must implement it using the ImageEditor API.
