### ISSUE TITLE
addText init options styles.fill doesn't work.

### ISSUE THREAD

**Issue by Aleczhang1992** [nhnent/tui.image-editor#37]
The addText init options styles.fill doesn't work.So I cant set the init color of the text.

**Comment by Aleczhang1992** [comment]
I find that u lost receive the fill option and merge with default styles. There is an error here.
<img width="912" alt="default" src="https://user-images.githubusercontent.com/15828753/40967754-79076234-68e6-11e8-829e-a5ebee3c2055.png">
<img width="885" alt="default" src="https://user-images.githubusercontent.com/15828753/40967779-8f5b2b6a-68e6-11e8-9317-d637daca867c.png">

**Comment by jinwoo-kim-nhn** [comment]
@Aleczhang1992 
thank you. The resolved code will be available as soon as possible.

**Comment by junghwan-park** [comment]
@Aleczhang1992 
Issue resolved.
