### ISSUE TITLE
이미지 파일이 아닌 다른 파일 로드 버그

### ISSUE THREAD

**Issue by ryum91** [nhnent/tui.image-editor#40]
이미지 파일이 아닌 파일을 로드하면 빈 화면이 나오게 됩니다.
그리고 나서 다시 일반 이미지 파일을 로드하면
로드가 되지 않습니다.

[샘플 페이지](http://nhnent.github.io/tui.image-editor/latest/tutorial-example01-includeUi.html)에서 테스트 하였습니다.

**Comment by jinwoo-kim-nhn** [comment]
감사합니다. 이 문제를 해결한 코드를 다음 배포에 포함시킬 예정입니다.
