### ISSUE TITLE
Looks great, but ..

### ISSUE THREAD

**Issue by shtefcs** [nhnent/tui.image-editor#43]
Let me tell you something as non developer. I am spending lot of time into Javascript OS ecosystem, and what is the biggest miss on every OS Repo is live demo link.

Is it to hard deploy app and have live working demo, which can see lot of entrepreneurs, marketing, design and other no technical people ? Which can directly impact of having your OS project getting even more exposure, PR's or paid work ?

Whatever, this is my honest and direct feedback to you and all other open source developers. 

Put the **Demo of your project online!** .

Peace,

**Comment by oleteacher** [comment]
Demo link is at very top of page:

Full-featured photo image editor using canvas. It is really easy, and it comes with great filters. http://ui.toast.com/tui-image-editor

**Comment by shtefcs** [comment]
Thanks for that @oleteacher , I honestly didn't see that link in the Repo summary.

I was looking at **table of contents** and didn't find in there.
