### ISSUE TITLE
Rotating the editor instance makes image disappear.

### ISSUE THREAD

**Issue by humblecoder** [nhnent/tui.image-editor#59]
Version

3.2.0

Development Environment

MacOS 10.12.6
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

Current Behavior

Using `editorInstance.rotate(degrees)` causes entire image/canvas to disappear.  The initial image is retrieved from URL on load.  I can save and reload images just fine.  I can also add text, draw, etc without issue.  However using `.rotate()` immediately makes the image disappear.  The number of degrees is irrelevant and reversing the rotation doesn't make it reappear.

**Comment by humblecoder** [comment]
I'm not sure if this is the "answer" but I've found that ***manually*** calling `resizeCanvas(width,height)` makes it reappear.  Hopefully someone has a better answer.  😕

**Comment by jinwoo-kim-nhn** [comment]
@humblecoder 

I want to help, but I can not reproduce it, so it is hard to help. But the expected part is that images with too large a resolution may be slow or not working well.

**Comment by jinwoo-kim-nhn** [comment]
@humblecoder 
I'm sorry. The issue related to the rotate function is a recently discovered problem that I had not anticipated recently.
`Perhaps` it is related to browser performance, so it is hard to solve.
I will try to improve on this problem.

**Comment by humblecoder** [comment]
@jinwoo-kim-nhn understood.  FYI, I've tested it in the following browsers:

`Chrome Version 69.0.3497.100 (Official Build) (64-bit)`
`Safari Version 12.0 (12606.2.11)`
`Firefox 62.0.3 (64-bit)`
`Opera Version:56.0.3051.36`

**Comment by humblecoder** [comment]
No longer seems to be an issue.
