### ISSUE TITLE
Can't update when select a drawing object

### ISSUE THREAD

**Issue by dhduc** [nhnent/tui.image-editor#71]
## Version
Latest version

## Development Environment
OS: Ubuntu 18.04
Browser: Chrome 69.0

## Current Behavior
After drawing a line, I switch to the texting mode, then chose that line object I drew before.
The drawing mode is enabled, but there are two issues happen:
1. I can't change the color of the line object.
2. I can't draw anymore unless I change the any draw options, or I need to quit the drawing mode then re-enable it to continue drawing.

![line-object](https://user-images.githubusercontent.com/11469236/46727425-c23bb680-ccaa-11e8-826a-3f65330917d8.png)

## Expected Behavior
Can you give me any hint to fix those issue?

**Comment by dhduc** [comment]
I figure out that when a drawing object activated, the draw menu is enabled, but also call the `changeStandbyMode()` to `stopDrawingMode()`, why is that needed?

```javascript
if (_this11.ui.submenu !== 'draw') {
    _this11.ui.changeMenu('draw', false, false);
    _this11.ui.draw.changeStandbyMode();
}
```

**Comment by jinwoo-kim-nhn** [comment]
@dhduc  This is the intended behavior. You can get it to work as you say, but it has received feedback that it's awkward in its own way.

This problem is a better way to help in a better way.

**Comment by dhduc** [comment]
@jinwoo-kim-nhn thanks for your feedback, I will do my own way to customizing behavior.
