### ISSUE TITLE
Can't Undo Crop

### ISSUE THREAD

**Issue by emyl3** [nhnent/tui.image-editor#77]
## Version
3.2.0

## Development Environment
Browser: Chrome Version 69
OS: macOS

## Current Behavior
After cropping an image and then clicking undo, a user cannot undo a crop and the crop rectangle remains and can't be deleted.
Can be reproduced in this example:
http://nhnent.github.io/tui.image-editor/latest/tutorial-example01-includeUi.html

Successfully crop and apply that crop. Then try to undo it. There is no way to remove the crop rectangle unless the entire image is reset.

## Expected Behavior
Clicking undo should remove the crop.

**Comment by jinwoo-kim-nhn** [comment]
This problem is solved.
