### ISSUE TITLE
it is not displaying any icon  giving an error like this-- tui-image-editor.js:5251 GET http://localhost:8100/icon-c.svg net::ERR_ABORTED

### ISSUE THREAD

**Issue by madhumatip** [nhnent/tui.image-editor#78]
## Current Behavior

```js
// Write example code
```

**Comment by Fridthjof** [comment]
Did you fix this problem? 

Currently i have the same issue.

**Comment by VitaliyOnRule** [comment]
I have the same problem

**Comment by sarlocktitans** [comment]
change the links of icon in tui-image-editor.js as per the icons exact location 
if you have place the dist file in public folder change all the links of icon in code like this -  
(the below link will get href="../dist/svg/iconname")
<use xlink:href=\"" + normal.path + "#" + normal.name + "-ic-text-bold\" class=\"normal\"/>\n
(the below link will get href="/dist/svg/iconname")
<use xlink:href=\"" + normal.path.replace('..','') + "#" + normal.name + "-ic-text-bold\" class=\"normal\"/>\n

**Comment by VitaliyOnRule** [comment]
actually the solutions is to rewrite theme icon paths
            'common.bi.image': 'img/some-path/some-imgi.svg',
            'menu.normalIcon.path': 'img/some-path/icon-d.svg'

**Comment by paulinhowoox** [comment]
I have the same problem.

**Comment by jinwoo-kim-nhn** [comment]
`npm run build: svg` creates the file under the dist / directory. The theme file should match its path.

**Comment by wombatastronaut** [comment]
Did anyone manage to solve this? The icons are not also displaying in my vue application. I already changed the path.
