### ISSUE TITLE
How do I use this on mobile devices?

### ISSUE THREAD

**Issue by brandoncc** [nhnent/tui.image-editor#98]
## Version
3.22

## Development Environment
iOS 12, Chrome browser

## Current Behavior
The editor is bigger than the screen dimensions and I can't scroll over to the save button. Even when I rotate my device and get to the button, it doesn't do anything when I tap on the button.

## Expected Behavior
I expect it to be usable on mobile devices.

**Comment by Langstra** [comment]
https://github.com/nhnent/tui.image-editor/blob/master/docs/Apply-Mobile-Version.md
